<?php

namespace AppBundle\Repository;

/**
 * ExportProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExportProductRepository extends \Doctrine\ORM\EntityRepository
{
}
