<?php

namespace AppBundle\Repository;

/**
 * exportShipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class exportShipRepository extends \Doctrine\ORM\EntityRepository
{
}
