<?php

namespace AppBundle\Repository;

/**
 * ImportOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
